CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    is_blocked BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS currency (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS accounts (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    user_id BIGINT REFERENCES users (id) ON UPDATE CASCADE ON DELETE NO ACTION,
    balance NUMERIC(19, 2) NOT NULL DEFAULT 0.0
);

CREATE TABLE IF NOT EXISTS accounts_history (
    id BIGSERIAL PRIMARY KEY,
    transaction_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    account_id BIGINT REFERENCES accounts (id) ON UPDATE CASCADE ON DELETE NO ACTION,
    spent_amount NUMERIC(19, 2),
    left_balance NUMERIC(19, 2)
);